server:
  port: 8888
spring:
  application:
    name: configure
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Adithya212/book-store-config.git
          clone-on-start: true
          skip-ssl-validation: true
logging:
  pattern:
    console: "%msg%n"
